#!/bin/bash

#$Destination=$1

echo "copy from Solution files from SAVEDISK"

# solution from :
# YYYY doy    week d
# 2004 003 => 1251 6
# 2004 004 => 1252 0
# 2004 005 => 1252 1
# 2004 006 => 1252 2
days="0 1 2 6"

for ((week=1251; week<=1774; week++)) 
do {
	for dow in $days
	do {
		yy=$(gps_date -wd $week $dow -o "%y")		
		doy=$(gps_date -wd $week $dow -o "%j")
		filename=$(echo "R1_$yy$doy""0.NQ0.gz")
		pathname=$(echo "$S/RNX2SNX/20$yy/SOL/$filename")
		cp $pathname .
		# cp $S/$pathname $Destination
	} done  
} done
