#!/bin/bash

file="/SOL/home/voelk/Python/igs_downloader/euref_sta.lst"
julian=`/SOL/home/voelk/bin/gps_date -t -o "%J" |awk '{printf"%i\n",$1}'`
echo $julian
#
#  Gestern
#
weekd="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24"
for week in $weekd
{
	julian=$((julian-1))
	doy=`/SOL/home/voelk/bin/gps_date -mjd $julian  -o "%j"`
	year=`/SOL/home/voelk/bin/gps_date -mjd $julian  -o "%Y"`
	echo $year $doy $file
	~/bin/igs_download.py -Y$year -D$doy -L$file
}
