#!/bin/bash

SITE=$1
inputFile=$2

echo "" > North
echo "" > East
echo "" > Up

grep $SITE $inputFile > $SITE.CRD
more $SITE.CRD | awk '{if ($4 == 1) printf"%-15.6f   %10.5f  %10.5f \n", $6, $5, $7}' > North_mjd
more $SITE.CRD | awk '{if ($4 == 2) printf"%-15.6f   %10.5f  %10.5f \n", $6, $5, $7}' > East_mjd
more $SITE.CRD | awk '{if ($4 == 3) printf"%-15.6f   %10.5f  %10.5f \n", $6, $5, $7}' > Up_mjd
rm $SITE.CRD

paste North_mjd East_mjd Up_mjd | awk '{printf"%-16s %10s %10s     %10s %10s     %10s %10s \n", $1, $2, $3, $5, $6, $8, $9}' > NEU_mjd

#rm North_mjd
#rm East_mjd
#rm Up_mjd 

while read line 
do {		
	line=($line)	
	MJD=$(echo ${line[0]})
	Date=$(gps_date -mjd $MJD -o "%Y-%m-%d")

	Res_N_m=$(echo ${line[1]})
	Res_N_mm=$(echo $Res_N_m*1000 | bc)
	RMS_N_m=$(echo ${line[2]})
	RMS_N_mm=$(echo $RMS_N_m*1000 | bc)

	Res_E_m=$(echo ${line[3]})
	Res_E_mm=$(echo $Res_E_m*1000 | bc)
	RMS_E_m=$(echo ${line[4]})
	RMS_E_mm=$(echo $RMS_E_m*1000 | bc)

	Res_U_m=$(echo ${line[5]})
	Res_U_mm=$(echo $Res_U_m*1000 | bc)
	RMS_U_m=$(echo ${line[6]})
	RMS_U_mm=$(echo $RMS_U_m*1000 | bc)

	echo "$Date  $Res_N_mm  $RMS_N_mm" | awk '{printf "%10s    %12.3f  %10.5f \n",$1, $2, $3}' >> North
	echo "$Date  $Res_E_mm  $RMS_E_mm" | awk '{printf "%10s    %12.3f  %10.5f \n",$1, $2, $3}' >> East
	echo "$Date  $Res_U_mm  $RMS_U_mm" | awk '{printf "%10s    %12.3f  %10.5f \n",$1, $2, $3}' >> Up

} done < NEU_mjd

NEU_mjd

echo "Done"










