#!/bin/bash

SITE=$1
inputFile=$2

rm -f North
rm -f East
rm -f Up

grep $SITE $inputFile > $SITE.CRD
more $SITE.CRD | grep ' 1  ' | cut --characters=37-41 > mjd_table.txt
grep -f mjd_table.txt time_table.txt | cut --characters=-10 > time.txt
more $SITE.CRD | awk '{if ( substr($0,23,1) == 1) printf "%10.5f  %10.5f \n", substr($0,25,10)*1000, substr($0,61,10)*1000}' > North.txt
more $SITE.CRD | awk '{if ( substr($0,23,1) == 2) printf "%10.5f  %10.5f \n", substr($0,25,10)*1000, substr($0,61,10)*1000}' > East.txt
more $SITE.CRD | awk '{if ( substr($0,23,1) == 3) printf "%10.5f  %10.5f \n", substr($0,25,10)*1000, substr($0,61,10)*1000}' > Up.txt

paste time.txt North.txt > North
paste time.txt East.txt  > East
paste time.txt Up.txt    > Up

rm $SITE.CRD
rm North.txt
rm East.txt
rm Up.txt
rm time.txt











